services:
  mariadb:
    restart: always
    build:
      context: ./requirements/mariadb/
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception-network
    container_name: mariadb
    secrets:
      - db_root_password
      - db_password
    environment:
      - MARIADB_PASSWORD=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD=/run/secrets/db_root_password
    image: mariadb:inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -h 127.0.0.1 -uroot -p\"$$(cat /run/secrets/db_root_password)\" ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    restart: always
    build:
      context: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    env_file: .env
    environment:
      - ADMIN_PASS=/run/secrets/admin_password
      - MARIADB_PASSWORD=/run/secrets/db_password
      - MARIADB_ROOT_PASSWORD=/run/secrets/db_root_password
    secrets:
      - db_root_password
      - admin_password
      - db_password
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1m
    image: wordpress:inception

  nginx:
    restart: always
    build:
      context: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    depends_on:
      wordpress:
        condition: service_healthy
    image: nginx:inception
    

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/data-base
  
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/data-website

secrets:
  root_user_password:
    file: ../secrets/db_root_user_password.txt
  admin_password:
    file: ../secrets/admin_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

networks:
  inception-network:
    name : inception-network
    driver: bridge
