FROM alpine:3.21.4

RUN apk update

RUN apk add --no-cache vsftpd

# COPY vsftpd.conf /etc/vsftpd.conf

# RUN mkdir -p /var/run/vsftpd/empty

EXPOSE 21 30001-30009  

CMD ["vsftpd", "/etc/vsftpd.conf"]